[layout]
direction = "horizontal"
tree_size = 40

[header]
disable = false
format = "{version} - {data_source} ({content_type}) - {data_size}"

[keys]
move_up = ["k", "<up>"]
move_down = ["j", "<down>"]
move_left = ["h", "<left>"]
move_right = ["l", "<right>"]
select_focus = ["<enter>"]
select_parent = ["p"]
select_first = ["g"]
select_last = ["G"]
close_parent = ["<backspace>"]
change_root = ["r"]
reset = ["<esc>"]
page_up = ["<page-up>", "<ctrl-y>"]
page_down = ["<page-down>", "<ctrl-e>"]
change_layout = ["v"]
tree_scale_up = ["["]
tree_scale_down = ["]"]
switch = ["<tab>"]
quit = ["<ctrl-c>", "q"]

[colors]
header = {bold = true}
focus_border = {fg = "magenta", bold = true}

[colors.tree]
border = {fg = "blue"}
selected = {fg = "black", bg = "light-green"}

[colors.item]
name = {}
type_str = {fg = "cyan", bold = true, italic = true}
type_null = {fg = "cyan", bold = true, italic = true}
type_bool = {fg = "cyan", bold = true, italic = true}
type_num = {fg = "cyan", bold = true, italic = true}
type_arr = {fg = "cyan", bold = true, italic = true}
type_obj = {fg = "cyan", bold = true, italic = true}
description =  {fg = "dark-gray"}
null = {fg = "dark-gray", italic = true}

[colors.data]
text = {}
border = {fg = "blue"}
symbol = {}
name = {fg = "yellow", italic = true}
str = {fg = "green"}
num = {fg = "red"}
null = {fg = "blue", italic = true}
bool = {fg = "red", bold = true, italic = true}
section = {fg = "cyan", bold = true}

[types]
str = "str"
null = "null"
bool = "bool"
num = "num"
arr = "arr"
obj = "obj"
